version: 0.0
os: linux
files:
  - source: /api
    destination: /var/www/api
hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu