version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/exp-nodejs
permissions:
   - object: /home/ubuntu/exp-nodejs
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/start.sh
      pattern: "**"
      owner: root
      group: root
      mode: 777
  AfterInstall:
    - location: scripts/start.sh
      timeout: 180