version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/exp-nodejs
permissions:
   - object: /home/ubuntu/exp-nodejs
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: Scripts/UnzipResourceBundle.sh
    - location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180