version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: script/install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu