version: 0.0
os: linux
files:
  - source: /api
    destination: /home/ec2-user/api
hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: script/install.sh
      timeout: 300
      runas: root
    - location: script/start.sh
      timeout: 300
      runas: root
    