module.exports = {
  LANGUAGE_KEYS: {
    ACTIVITY_MICRO_SERVICE: "ACTIVITY.MICRO_SERVICE",
    ACTIVITY_UNAUTHORIZED: "ACTIVITY.UNAUTHORIZED",
    ACTIVITY_FORBIDDEN: "ACTIVITY.FORBIDDEN",
    ACTIVITY_INTERNAL_SERVER_ERROR: "ACTIVITY.INTERNAL_SERVER_ERROR",
    ACTIVITY_NOT_FOUND: "ACTIVITY.NOT_FOUND",
    ACTIVITY_NEW_ANNOUNCEMENT: "ACTIVITY.NEW_ANNOUNCEMENT",
    ACTIVITY_NEW_EVENT: "ACTIVITY.NEW_EVENT",
  },
  STATUS: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED",
    DELETED: "DELETED",
  },
  PAGE_LIST_LIMIT: 10,
  DEFAULT_PHOTO: "https://picsum.photos/200",
};
